### ISSUE TITLE
Renaming the CLI to be `create-component`

### ISSUE THREAD

**Issue by labithiotis** [CVarisco/create-component-app#10]
Personally, I think the CLI should be `create-component` as it's not making an app but understand you adopted it from `react-create-app` and `create-component` was already [taken](https://www.npmjs.com/package/create-component). 

Would you be open to supporting both, by just adding another bin path in package.json ?

**Comment by richraid21** [comment]
If you install the package globally, you can just create an alias in your bash_profile: 
`alias create-component="create-component-app"`

**Comment by CVarisco** [comment]
Hi @labithiotis,
the package is `create-component-app` because is similar to `create-react-app`.
I think it's the best to understand what it means (and the context, react).

Thanks a lot for your suggestion.
I'm closing the issue.
