### ISSUE TITLE
adds the ability to add component lifecycle methods on pure and class component

### ISSUE THREAD

**Issue by CVarisco** [CVarisco/create-component-app#14]
It would be great if it is possible to adds all (for now) component lifecycle methods on class and pure component template.

**Comment by TryingToImprove** [comment]
Just want to mention that I normally have my `componentDidMount` as a `async` function.

I am not sure if it should handle that.

**Comment by CVarisco** [comment]
Hi @TryingToImprove,
for this specific case I think that now you can use custom template.

It is very difficult to do default templates that can fulfill every single developer.
But thanks a lot for your suggestion, for me it is very important receive feedbacks 🙂

**Comment by CVarisco** [comment]
Hi @TryingToImprov, 
I reliased a feature to insert methods inside pure and class components.
Check it out, And if you want, tell me what do you think about it 👍
