### ISSUE TITLE
Doesn't apply rules from .ccarc

### ISSUE THREAD

**Issue by viktorbergehall** [CVarisco/create-component-app#15]
I have created a `.ccarc` file in the root of my project folder with the following config:
```
{
    "path": "./src/components",
    "jsExtension": "js",
    "cssExtension": "scss",
    "includeTests": true,
    "includeStories": true
}
```
The problem is that the cli doesn't seem to apply that config.

I run create-component-app@0.6.0 with npm@5.0.3. I do not have a global config file.

**Comment by CVarisco** [comment]
Hi @viktorbergehall!

the problem is that now the library check the file inside the folder `.ccarc` not the file.
Try to create a folder with `.ccarc` name and put inside a `config.json` file.

Let me know 👍 
thanks for your support 🙂

**Comment by viktorbergehall** [comment]
Works great! Thank you for the fast reply

**Comment by CVarisco** [comment]
I need to edit the documentation (because is not clear enough) or add the ability to get a `.ccarc` file in the project folder 👍 
Thank you again 🙂
