### ISSUE TITLE
Add support for flow annotations

### ISSUE THREAD

**Issue by monsonjeremy** [CVarisco/create-component-app#21]
Add a flag to add flow annotations which would enable flow at the top of the file and put in some default flow type annotations like so: 

```
// @flow

type Props = {}

class SomeClass extends PureComponent {
  constructor(props: Props) {
     super(props)
  }
}
```

**Comment by CVarisco** [comment]
Hi @monsonjeremy,

thanks a lot for your support 👍🏻
Yeah, this will be a great enhancement in the config file.
Now we have a lot of questions on the CLI, so I think it is better to put this option only in the configuration.
What do you think about it ?

If you want contribute, for me it's a pleasure 🙂

**Comment by CVarisco** [comment]
Hi guys,
now you can create custom templates with this tool!
Here the docs: [Link](https://github.com/CVarisco/create-component-app/blob/master/docs/CUSTOM-TEMPLATES.md)

And also, you can share it with the community!!!
Here the docs: [Link](https://github.com/CVarisco/create-component-app/blob/master/docs/CUSTOM-TEMPLATES-COMMUNITY.md)

Thanks a lot for your support 🏆
