### ISSUE TITLE
[Question] Roadmap / new features?

### ISSUE THREAD

**Issue by nealoke** [CVarisco/create-component-app#29]
Hi @CVarisco I was just wondering, what are the next steps for this project? I might want to contribute some more :)

**Comment by CVarisco** [comment]
Hi @nealoke !
I'm very happy that you want contribute more 🙂 
You can choose whatever you want from the issue list ( #5, #7 or #21 )

Or, if you have other ideas, we can talk about it 💪

**Comment by nealoke** [comment]
Yhea I was thinking why is this only "limited" to react components? In my opinion it could easily extend to redux. But it might be easier to just create a project which takes template files from different folders based on some questions via the CLI

Also it might be nice to also be able to provide which things to replace in stead of the only `COMPONENT_NAME`.

**Example folder structure**
- config.json
- myTemplates
  - component
  - reducer

**Example `config.json`**
```
{
	type: "custom",
	"templatesPath": "./myTemplates",
	"subsituteData": {
		"component": [
			"COMPONENT_NAME",
			// ... other things you want to replace
		],
		"reducer": [
			"ACTIONS",
			// ... other things you want to replace
		]
	}
}

```

**Example CLI**
- `create-component-app`
- Which templates would you like to use? **component**
- Replace `COMPONENT_NAME` with? **myComponent**
- ... other things you want to replace
- Your files are created!

I think this would allow this tool to be used in different things then just react components but on the other hand it might be overkill. Let me know 👍  If it is overkill I'll probably write it as a separate project :)

**Comment by CVarisco** [comment]
Hi @nealoke !

I like your idea and could be very useful, in fact, me and @puemos will do a proposal regarding managing custom templates in this issue.
It would be great if you could give your feedback 👍

**Comment by nealoke** [comment]
@CVarisco @puemos any updates on this? :)

**Comment by CVarisco** [comment]
Hi,

I'm in vacation now 🏝
@puemos started #30.

If you want to contribute on him branch, check it out!

Ps:I'm coming back on September 🙃

**Comment by CVarisco** [comment]
Hi @nealoke 
@puemos are working on #30 and it is almost finished!

I'm closing this issue 🙂 
Check the update soon
