### ISSUE TITLE
Templates Mgmt

### ISSUE THREAD

**Issue by puemos** [CVarisco/create-component-app#30]
Templates Mgmt
=============

The inspiration for this feature is [oh my zsh plugins](https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins) mgmt

#### Requests:

1. Offer a set of predefined templates
2. Enable the user to add or edit custom templates
3. User can choose a template upon creation

#### Resentments

1. Ensure the quality of the predefined templates
2. Restrict the number of the suggested templates (so you don't have to choose between 100 templates)

#### Development

- [x] Create a templates dir that will contain the predefined templates. 
- [x] Add to the setting `templatesDirPath` - a custom path to the user custom templates folder.
- [x] The user can choose between the available templates or use `create-component-app -t templateName`
- [x] Add to the setting `templates` - a list of used templates (with a default)
- [x] On init the app will read the set `templates` and will validate them with `predefinedTemplates` and `templatesDirPath`.
- [x] The community can offer their templates

https://github.com/puemos/create-component-app

https://github.com/puemos/create-component-app/blob/master/docs/CUSTOM-TEMPLATES.md

![predefined](https://user-images.githubusercontent.com/13174025/28995885-02d9bc28-79f5-11e7-99e8-ae42343ec1cf.gif)
![normal](https://user-images.githubusercontent.com/13174025/28995884-02d8947e-79f5-11e7-9d00-9a81ce75f5d3.gif)

**Comment by CVarisco** [comment]
Very cool stuff!
Thanks a lot @puemos  👍

**Comment by CVarisco** [comment]
Hi @puemos !
Any update on this ?

**Comment by puemos** [comment]
Hey @CVarisco ! 

I think it's almost ready, care to take a look?
We need some manual testing

**Comment by CVarisco** [comment]
Sure @puemos 

I'm cloning and testing now 🙂 
After that, I text to you again 💯
