### ISSUE TITLE
SyntaxError: Unexpected token { at \create-component-app\dist\index.js:69

### ISSUE THREAD

**Issue by vaiulian** [CVarisco/create-component-app#4]
I'm getting a `SyntaxError: Unexpected token {`

`C:\Users\vaiulian\AppData\Roaming\npm\node_modules\create-component-app\dist\index.js:69`
`function generateFiles({ type, name, path, indexFile, cssExtension, jsExtension, connected }) {`
                       ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

i tried with config file as well.

L.E. 
node --version v4.5.0
npm --version 2.15.9

**Comment by CVarisco** [comment]
Hi @vaiulian,
I used a new ES6 feature and I choose v7 of node to the minimum.
If you don't want update your node version, I can set v4 the minimum version of node.

ps: My tip is update the version to have a lot of new features and improvements of node 🙂

**Comment by vaiulian** [comment]
No, i can't update to v7 and break my environment, not yet. The latest LTS version is 6.11 so i guess i'll update to that. 

Also i think you should consider some retro compatibility. That way the tool will have a higher adoption rate.

Otherwise looks good.

**Comment by CVarisco** [comment]
You are right!
in the next release i downgrade the minimum version to v6.

Thanks for your suggestion.

**Comment by CVarisco** [comment]
Hey @vaiulian in the v0.3.0 the target node version is 6 🙂
Thanks again!
