### ISSUE TITLE
Ability to create a component without creating it's parent directory?

### ISSUE THREAD

**Issue by mdxprograms** [CVarisco/create-component-app#46]
If I have a `components/` directory and want to just create a file in that directory when running the script can I do that with the current implementation?

so if I run `create-component-app -t container` and call it `NavContainer` can I get it to create it under `components/NavContainer.js` instead of `components/NavContainer/NavContainer.js`

**Comment by CVarisco** [comment]
Hi @mdxprograms,

I'm sorry about that but you can't do this.
How can the tool know if the component file should be copied directly or not? There is no a "dynamic way" to know if the user wants a single file or a folder (the only way is to ask to him, but it's another question).
Do you have some solution in mind?

If you don't understand what I mean, I'm here for any question 🙂 
Thanks a lot for your question 👍

**Comment by puemos** [comment]
Hey @CVarisco @mdxprograms ,

Maybe we can create an optional config file in the base directory of the template with specific configs for it.
When we use the template first we read the config and then we can generate the components by them.

1. create directory or not
2. set of extra questions
3. ...

### .config.yml
```yml
dir: bool
questions: Array<Question>,
...etc
```

**Comment by CVarisco** [comment]
Very cool idea @puemos!
This is what I mean before, the only way to do that is with a user input and this could be a great idea 🙂 

What do you think @mdxprograms ?

**Comment by mdxprograms** [comment]
ya I think this is probably a solid idea for this. I worked on my a custom generator as well (thank you especially for the inspiration) and made it where the `templatesDir` is just referenced as the base directory for the templates. So you can do 1 of the following:

`react-do component People`

and

`react-do component People/Person`

**Comment by CVarisco** [comment]
Hey @mdxprograms !

@puemos implement the capability to put a config file in the custom template folder! 
Here the doc: [Link](https://github.com/CVarisco/create-component-app/blob/master/docs/CUSTOM-TEMPLATES.md#4-create-your-templates)

thanks again @mdxprograms and @puemos for the support 🏆

**Comment by mdxprograms** [comment]
Thanks @CVarisco
