### ISSUE TITLE
Support for TypeScript components

### ISSUE THREAD

**Issue by pulverize** [CVarisco/create-component-app#47]
TypeScript is viewed as a viable means of type enforcement in React apps. All the components in my project are .tsx, and all the store files are .ts. I'd try out create-component-app if it had this functionality and it shouldn't be _too_ difficult to implement.

**Comment by CVarisco** [comment]
Hi @pulverize !

thanks a lot for your help 🙂 
Now, you can create a custom template and you can share it with the community also.

Otherwise, could you explain better what kind of feature do you have in mind?
Thanks man 💯

**Comment by CVarisco** [comment]
I'll close the issue because the capability to have .ts files exists 👍
