### ISSUE TITLE
Static `defaultProps` and `propTypes`

### ISSUE THREAD

**Issue by TryingToImprove** [CVarisco/create-component-app#5]
Instead of having `${COMPONENT_NAME}.propTypes = {}` it would be nice if it was

```js
class ${COMPONENT_NAME} extends Component {
    static propTypes = {};
    static defaultProps = {};
    //.....
}
```

**Comment by CVarisco** [comment]
Hi @TryingToImprove,
thanks a lot for your suggestion.

I'm working on custom template feature.
In this way you can create your template and use it with the library.

What do you think about it ?

**Comment by TryingToImprove** [comment]
@CVarisco It seems like it is going to require a lot of setup for the consumer/user. It would be nice if it was just like a addition to create-react-app, which have support for static properties;

https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#supported-language-features-and-polyfills

**Comment by CVarisco** [comment]
Hi @TryingToImprove,

yesterday I added the custom template feature. If you want, try it and would be great if you give me some feedback.
I'm adding the label "enhancements" for this issue :)

Thanks

**Comment by CVarisco** [comment]
Hi @TryingToImprove,
Check this #30 that can help you !

I'm closing this.
