### ISSUE TITLE
Change file naming format for tests

### ISSUE THREAD

**Issue by ddrabik** [CVarisco/create-component-app#57]
The convention I use for naming tests in my project is `COMPONENT_NAME.test.js`. The script generates test files in the format of `test.COMPONENT_NAME.js`. 

Do you think the format should be exposed as a `.ccarc` option?

**Comment by CVarisco** [comment]
Hi @ddrabik and @Ayc0,
thanks a lot for your support, I appreciate your feedback 🙂 
Could better use the `fileNames.testFileName` option.

What do you think about it?

**Comment by ddrabik** [comment]
I think either one handles the majority of use cases. I like the proposal by @CVarisco b/c you can eliminate `fileNames.testFileName` and `fileNames.testFileMatch`.

Whichever one we go with, I could also see this used for the style and storybook file naming.

**Comment by CVarisco** [comment]
I'll work on the fileNames fix asap.

Thanks guys 🥇

**Comment by CVarisco** [comment]
Hi @ddrabik @Ayc0,

I published a new version of the new feature (v1.6.0).

Now you can call the testFileName like you want and I added the capability to use COMPONENT_NAME on the filenames options.

What do you think? Can you test if for you is a good option?

Thanks guys 👍
