### ISSUE TITLE
there's no `--path` param

### ISSUE THREAD

**Issue by croogie** [CVarisco/create-component-app#58]
I'd like to run generator providing `path` parameter from commandline (not from config file). 
It would be great to have ability to provide almost every parameter from commandline so that script can be easily integrated with IDEs.

**Comment by CVarisco** [comment]
Hi @croogie !
thanks a lot for your support, makes the community a better place 🙂 

Sure, you have a good idea! 
I'll work on this asap 👍 

Thanks 🌮

**Comment by croogie** [comment]
Is there a way how I can test that change locally? NPM link?
