### ISSUE TITLE
add prettier-eslint hook to lint the components with the rules of the project

### ISSUE THREAD

**Issue by CVarisco** [CVarisco/create-component-app#7]
It would be great if the new component is already linted with the rules of the project !

thank you @cedmax for the tip!

**Comment by labithiotis** [comment]
A different way I was going to tackle this was to run [prettier](https://github.com/prettier/prettier) over all generated files using rules defined in default config.

I was also thinking there's no need to ask the question to run prettier, just assume if someone has it defined in their default config it would always run it.

**Comment by cedmax** [comment]
I would use prettier-eslint, I would think eslint is way more common than
prettier (I might be wrong tho).

**Comment by nealoke** [comment]
@CVarisco +1 for this :) I would just use rules of eslint or if you can. Prettier is mostly hooked in with eslint in my opinion :)

**Comment by CVarisco** [comment]
Hi guys,
now you can create custom templates with this tool!
Here the docs: [Link](https://github.com/CVarisco/create-component-app/blob/master/docs/CUSTOM-TEMPLATES.md)

And also, you can share it with the community!!!
Here the docs: [Link](https://github.com/CVarisco/create-component-app/blob/master/docs/CUSTOM-TEMPLATES-COMMUNITY.md)

Thanks a lot for your support 🏆
