### ISSUE TITLE
support for typescript

### ISSUE THREAD

**Issue by isabolic** [CVarisco/create-component-app#71]

**Comment by CVarisco** [comment]
Hi @isabolic !

you can create your own template with the support of typescript.
If you want, I can send here an example if you send me a template 🙂

**Comment by isabolic** [comment]
@CVarisco if you can attach template example of ts here that would be great. 👍 

Tnx

**Comment by CVarisco** [comment]
@isabolic depends on your way of doing components.
Post here an example of your component please :)

**Comment by isabolic** [comment]
import * as React from "react";
import AppBar from "material-ui/AppBar";
import Toolbar from "material-ui/Toolbar";
import IconButton from "material-ui/IconButton";
import MenuIcon from "material-ui-icons/Menu";
import AccountCircle from "material-ui-icons/AccountCircle";
import Switch from "material-ui/Switch";
import Typography from 'material-ui/Typography';
import { FormControlLabel, FormGroup } from "material-ui/Form";
import Menu, { MenuItem } from "material-ui/Menu";

export class AppNavBar extends React.Component {
  render() {
    return (
        <AppBar>
          <Toolbar>
            <IconButton color="inherit" aria-label="Menu">
              <MenuIcon />
            </IconButton>
            <Typography variant="title" color="inherit">
              xxxxssdss
            </Typography>
          </Toolbar>
        </AppBar>
    )
  }
}
