### ISSUE TITLE
Template Creation Docs Are Unclear

### ISSUE THREAD

**Issue by damiansilbergleithcunniff** [CVarisco/create-component-app#72]
* The instructions are not clear enough about what is required and optional.
* I'm unsure if the example/s provided in the docs are complete
  * The config appears to only require 2 lines but I don't know if this is a partial or full config
* It's unclear to me that the `templateName` config key is supposed to point to
* "You can create a config file in your template directory"
  * I thought I already made the config file... if not, what should go in here? 
  * "Can" implies that this is optional? 
* The error message I get after following the docs doesn't provide enough information to understand what's gone wrong: 
  * `EISDIR: illegal operation on a directory, read`
  * Unsure what directory it is trying, and failing, to read
It would be INCREDIBLY helpful if the project came with a working example of a template directory.  It is probably also worth going over the documentation to ensure that it is as clear as possible.  

I REALLY like this project and as I onboard a few new devs I want to enforce the code standards by giving them templates to work with.  Help me help them.

**Comment by damiansilbergleithcunniff** [comment]
So I just fixed my issue by removing the `.ccarc` folder and `config.json` which was under it.  I then added a `cca` key to my `package.json` and added the block from the documentation bullet **2**.

My problem is resolved, but I think the docs still need attention.  I'd update them but I'm not certain I'm qualified.

**Comment by CVarisco** [comment]
Hi @damiansilbergleithcunniff 

I'm really sorry for the confusion that you found in the docs.
I'm changing the [CUSTOM_TEMPLATE](https://github.com/CVarisco/create-component-app/blob/master/docs/CUSTOM-TEMPLATES.md) documentation because as you notice is not correct (is referred to an old version of the tool)

I appreciate a lot your warning, thanks 🙏 
Feel free to tell me what do you think about it 🙂
