### ISSUE TITLE
Control Case Of Template Name

### ISSUE THREAD

**Issue by damiansilbergleithcunniff** [CVarisco/create-component-app#73]
I'm trying to use create-component-app for some of the other templated files I create.  Specifically redux actions, reducers, and selectors.  I'd like to be able to use the COMPONENT_NAME replacement key with different casing.  Currently it just uses whatever I've entered as the component name. 

What I'd love to be able to do is: 
* Specify: `ComponentName` on the command line
* In the template specify something like: `_component_name_` for an `lcased` version of the `ComponentName`
* in the template specify something like `_COMPONENT_NAME_` for a `ucased` version of the `ComponentName`
* in the template specify something like `_Component_Name_` for a raw output of the `ComponentName`

**Comment by CVarisco** [comment]
Hi @damiansilbergleithcunniff,

thank you for your suggestion 🙂 
I believe that now made these changes could be very difficult.
The API of `COMPONENT_NAME` is used by all the users and it is like that in every template.

I prefer to don't touch that API for now.
Thanks man 👍
